spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/cakefactory
        username: postgres
        password: admin
        driverClassName: org.postgresql.Driver
        initialization-mode: always
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL10Dialect
        hibernate.ddl-auto: update # When you launch the application for the first time - switch "none" to "create"

